# Site settings
title: Atomic Design by Brad Frost (JA)
email: brad@bradfrost.com
description: > # this means to ignore newlines until "baseurl:"
  デジタルデザインシステムの構築・維持手法を学び、チームがより高品質で一貫性のある UI をかつてないほど迅速に公開できるように。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bradfrost.com" # the base hostname & protocol for your site
twitter_username: brad_frost
github_username:  bradfrost
product_link: https://shop.bradfrost.com

# Build settings
markdown: kramdown
exclude: ["node_modules", "Gruntfile.js", "package.json", "_sass", ".sass-cache", ".DS_Store"]
port: 4200
